Added missing requirement to org.eclipse.equinox.launcher in test bundles
Launching org.eclipse.pde.junit.runtime.tests.JUnitRuntimeTests or
org.eclipse.pde.ui.tests.launcher.PluginBasedLaunchTest from Eclipse
results in the following exception:

org.eclipse.core.runtime.CoreException: Launching failed. Bootstrap code
cannot be found.

Adding org.eclipse.equinox.launcher to the required bundles of
org.eclipse.pde.junit.runtime.tests and org.eclipse.pde.ui.tests avoids
these errors.

Fixes: #2024