Catch NoClassDefFoundError while locating sources
If the locator is unable to locate some sources due to a classlaoding
problem this currently leads to an ugly exception window showing up.

This now adds NoClassDefFoundError to the catch clause to prevent annoy
the user in such case.