Add missing dependency for PDE Runtime to PDE Core
PDE Runtime has a transitive dependency to PDE Core via PDE UI. However,
that dependency is optional and some relevant functionality (like the
Plug-in Selection Spy) work without the PDE UI dependency but require
PDE Core. In an installation that contains PDE Core but not PDE UI, the
Plug-in Selection Spy will not work as the PDE Core dependency is not
resolved (as it needs to be resolved transitively via the non present
PDE UI dependency), thus leading to NoClassDefFoundErrors for required
classes from PDE Core.

This change adds the missing dependency.