Fixes NPE during shutdown of the an RCP application
In a client implementation I see the NPE from below. This adds a null
check for this.

java.lang.NullPointerException: Cannot invoke
"org.eclipse.swt.widgets.Button.isDisposed()" because
"this.createRemoveMainMenu" is null
	at org.eclipse.e4.tools.emf.ui.internal.common.component.WindowEditor.lambda$0(WindowEditor.java:369)