Adjust lower bound for dependency to JDT Launching in PDE Build
The PDEState class is using JavaRuntime.getProvidedVMPackages(...),
which has only been added with version 3.22. But the Manifest still only
requires 3.21. This causes issues when installing the latest PDE in the
Eclipse 4.31, as the JDT bundles are not updated, which therefore leads
to a NoSuchMethodError.

See https://github.com/eclipse-windowbuilder/windowbuilder/issues/865
for a real-life example of this problem.

Amends 42d3cf5a43fc630c940480813199c0d0200b8cc8